server:
  port: 8080
spring:
  profiles:
    active: dev #기본적으로 dev 환경임을 명시
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basic1__div?useUnicode=true&characterEncoding=utf8
    username: root
    password: qkr96#
  jpa:
    hibernate:
      ddl-auto: create  #create update

    properties:
      hibernate:
        show_sql: true #sql ??
        format_sql: true  #sql ? ?? ?? ???
        use_sql_comments: true #SIUD ? ?? ?? ??????
